### ISSUE TITLE
[bug] form 태그 제출시 선택하지 않은 것 있으면 알림 메세지 뜨는 부분 사라진 버그 

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/hkb-6#100]
## Description
>  금액과 내용만 유효성 검사가 작동하고 나머지 부분 유효성 검사 사라짐

**Comment by Pigrabbit** [comment]
`select` element 문제인가요?

**Comment by Pigrabbit** [comment]
아마 transaction edit하는 로직 추가하면서
조건식에서 `value === "default"` 조건을 빼서 그런거같아요

**Comment by haerang94** [comment]
> 아마 transaction edit하는 로직 추가하면서
> 조건식에서 `value === "default"` 조건을 빼서 그런거같아요

내일 추가 작업해야겠네요 ㅎ_ㅎ
