### ISSUE TITLE
통계페이지 월간이동시 그래프가 새로 그려지지 않는 버그

### ISSUE THREAD

**Issue by Pigrabbit** [woowa-techcamp-2020/hkb-6#101]
## Description
> 통계페이지에서 navbar로 월간이동시 그래프가 새로 그려지지 않습니다

**Comment by haerang94** [comment]
월간 이동시 다시 data fetch 하는 코드를 넣어야 겠어요

**Comment by Pigrabbit** [comment]
ㅎㅎ 작업중입니다

**Comment by haerang94** [comment]
> ㅎㅎ 작업중입니다

앗 아직 안자시네요,, 저는 슬슬 자려구요 😂 내일 봬요
