### ISSUE TITLE
aws 인스턴스 생성 및 CD 배포 구현

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/hkb-6#18]
## Description
> 인스턴스를 생성하여 mysql을 연결해 서버를 띄우고 CD를 구현합니다

- [x] 인스턴스 생성
- [x] CD 파이프라인 구축
- [x] `.env` 개발용 ↔  production용 구분하기

**Comment by Pigrabbit** [comment]
- CD 파이프라인 구축했으나 디버깅이 필요합니다 ㅜㅜ
- 개발용, 배포용 환경설정 분리는 다른 이슈로 분리해보겠습니다!
