### ISSUE TITLE
[hotfix,ledger] 새로운 가계부 입력시 수입 / 지출에 따라 색깔이 바뀌지 않는 버그

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/hkb-6#43]
## Description
> 새로운 가계부 생성시 지출과 수입에 따라 색깔이 변하지 않는데 추가 구현해야할 것 같습니다

**Comment by Pigrabbit** [comment]
아직 Form 컴포넌트에서 새로운 transaction생성 시 t_type을 지정해 주지 않는 것으로 알고 있습니다.
API응답 처럼 `t_type`이 "지출" 인지, "수입"인지 지정해주면 해결할 수 있을 것 같아요

**Comment by haerang94** [comment]
개발 완료
