### ISSUE TITLE
[hotfix,ledger] .env.dev 의 환경변수를 가져오지 못하는 문제

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/hkb-6#44]
## Description
> .env.dev의 API_URL이 undefined로 인식됩니다. 추가로 설정할 것이 있을까요?? 확인부탁드립니다

**Comment by Pigrabbit** [comment]
`.env.dev`의 경로가 `client/`바로 밑에있는지 확인해주세요!
`client/src/`아래있다면 이동시켜주세요!

**Comment by haerang94** [comment]
빌드 다시 하고 하니까 되네요 감사합니다
