### ISSUE TITLE
결제 수단을 삭제 했을때 p_id가 걸려있는 transaction 테이블의 모든 레코드 삭제

### ISSUE THREAD

**Issue by Pigrabbit** [woowa-techcamp-2020/hkb-6#74]
## Description
> `as is`: table을 정의할 때  준 `cascade` 옵션 때문에 삭제되는 결제수단을 가지고 있던 transaction 레코드들이 전부 삭제 됩니다.
> `to be`: 비즈니스 로직을 고민해 봐야 할 것 같습니다.

- [ ] 
- [ ]
- [ ]

**Comment by haerang94** [comment]
아 그런 버그도 있군요
