### ISSUE TITLE
[bug] 주소를 쳐서 calendar로 들어갈 경우 달력에 내역이 나오지 않는 버그

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/hkb-6#79]
## Description
>  navbar로 이동할 경우에는 잘 나오는 데 검색창에 주소를 쳐서 들어갈 경우에는 달력에 아무것도 뜨지 않는 버그를 발견했습니다

**Comment by Pigrabbit** [comment]
개발 서버에서인가요? 배포 서버에서인가요?

**Comment by Pigrabbit** [comment]
흠 확인했습니다 아마 `fetchLedgerItem()` 을 하는 시점 때문에 그런 것 같아요

**Comment by Pigrabbit** [comment]
#83 이 PR에서  해결했습니다!
