### ISSUE TITLE
[bug, hotfix] calendar, statistics 페이지에서 달력 이동시 숫자가 바뀌지 않는 버그 생김

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/hkb-6#94]
## Description
> list page에서는 달력 이동시 숫자가 변경이 되는데 calendar, statistics 페이지에서는 숫자가 8월에서 바뀌지 않습니다 . 또 다른 달로 이동하여 데이터가 없는 경우에는 통계 페이지에서 빈 페이지로 보여주는데 대신 보여줄 화면이나 문구를 집어넣어야 될 것 같습니다.

- [ ] 달력 숫자 안바뀌는 버그 수정
- [ ] 지출 없는 달은 대신 집어넣을 ui 생성하기
- [ ] 통계 페이지에서 날짜가 바뀌었을 때 fetchLedgerItem 다시 가져오는 로직 구현하기

**Comment by Pigrabbit** [comment]
이런 UI 어떤가요?

![image](https://user-images.githubusercontent.com/13795717/89551685-2ea38480-d846-11ea-92e6-6f52393356dc.png)

**Comment by haerang94** [comment]
좋아요

**Comment by Pigrabbit** [comment]
흠 `Filter` 컴포넌트가 `currentDate`를 구독하지 않고 있는것같군요...
손좀봐주고 올게요 👌🏻
